spring:
  main:
    allow-bean-definition-overriding: true
  
  resources:
    static-locations:
      - 'classpath:resources/static'

server:
  port: 8090
  servlet:    context-path: /travel

security:
  oauth2:
    client:
      clientId: travel-api-client
      clientSecret: psw
      accessTokenUri: http://localhost:8080/oauth/token
      tokenName: access_token
      grant-type: client_credentials
      
management:
#  server:#    port: 8091  endpoint:    httptrace:      enabled: true
    health:      show-details: always
    metrics:      enabled: true
    prometheus:      enabled: true
      
  endpoints:    web:
#      base-path: "travel"      exposure:        include: "*"
  metrics:
    distribution:      percentiles-histogram:        http:
          server:
            requests: true    enable:      jvm: true           export:      prometheus:        enabled: true
                   
                              